### ISSUE TITLE
Change the logo 

### ISSUE THREAD

**Issue by plon-Susk7** [plon-Susk7/Job-Board#10]
There's logo.svg file on public folder inside src. Change the website's logo from default logo to the one provided in the folder. Some svg code changes may be required.

**Comment by monish-j** [comment]
Hi, I'd like to work on this issue. Is it still open for contribution?

**Comment by plon-Susk7** [comment]
hi @monish-j , feel free to work on this issue. Let me know if you have any doubts.

**Comment by monish-j** [comment]
Hi @plon-Susk7,

I noticed that the `public` folder is located outside the `src` folder. The `index.html` file inside the `src` folder references the `logo.svg` file from the `public` folder.

Could you please confirm if the `logo.svg` file in the `public` folder outside the `src` folder is the one we should update? Or is there another `logo.svg` file that we should be using?

Also, could you provide the new logo SVG file or let me know where I can find it?

Thank you!

**Comment by plon-Susk7** [comment]
Please use the one in public folder :)

**Comment by monish-j** [comment]
Hi @plon-Susk7,

I noticed that the `index.html` file is already referencing the `logo.svg` file in the `public` folder. Could you please confirm if there are any specific changes needed for the `logo.svg` file, or if it is already up to date?

Thank you!

**Comment by monish-j** [comment]
Hi @plon-Susk7,
I created a pull request titled "Update logo and adjust CSS for proper display" (#14). I forgot to include an update to the index.html file to change the favicon path. The new path is:
<link rel="icon" type="image/svg+xml" href="./src/assets/logo.svg" />

Could you please review and merge this additional change?

Thank you!

**Comment by monish-j** [comment]
Hi @plon-Susk7,

I've pushed an additional commit to #14 to update the index.html file with the new favicon path. Please review and merge when convenient.

Thanks!
