### ISSUE TITLE
Add 10 links to repos funded by GSOC

### ISSUE THREAD

**Issue by plon-Susk7** [plon-Susk7/Job-Board#13]
Add links to src/scrapper/repos.yml file.

**Comment by monish-j** [comment]
Hi plon-Susk7

I'm interested in working on the issue "Add 10 links to repos funded by GSOC" (#13). Could you please assign it to me?

Thanks, monish-j

**Comment by plon-Susk7** [comment]
Go ahead @monish-j

**Comment by monish-j** [comment]
Hi plon-Susk7

I have added 10 links to repositories funded by Google Summer of Code (GSoC) in the src/scrapper/repos.yml file as requested in issue #13. I have already pushed the changes and created a pull request titled "Add 10 links to GSoC funded repositories in repos.yaml".

Could you please review and merge this update?

Thanks, monish-j

**Comment by monish-j** [comment]
Hi plon-Susk7

Should I use the API format (e.g., https://api.github.com/repos/...) or the standard GitHub format (e.g., https://github.com/...) for the new links?

Thanks, monish-j

**Comment by monish-j** [comment]
Hi plon-Susk7

I previously submitted non-working API URLs for the GSoC links. I have now updated the repos.yml file with the correct API links. Could you please review and merge this update?

Thanks, monish-j
