### ISSUE TITLE
Submitting a Link directly via Website

### ISSUE THREAD

**Issue by 0xTaneja** [plon-Susk7/Job-Board#15]
Description says submitting a repository link directly via website, but on the website there's no option. when clicked on submit button, it get's to github issues tab.

**Comment by plon-Susk7** [comment]
I am planning to create GitHub issues template for this. Would you like to work on that?

**Comment by 0xTaneja** [comment]
@plon-Susk7 yeah sure, I would love to !!

**Comment by plon-Susk7** [comment]
Give me some time, I'll break down the steps for you.

**Comment by 0xTaneja** [comment]
@plon-Susk7 yeah sure take your time !!
