### ISSUE TITLE
Add 10 YC open source company links

### ISSUE THREAD

**Issue by plon-Susk7** [plon-Susk7/Job-Board#18]
Add repo links to src/scrapper/repos.yaml file.

**Comment by monish-j** [comment]
Hi plon-Susk7,

I noticed the new issue #18 about adding 10 YC open source company links to the src/scrapper/repos.yaml file. I have created a branch named add-yc-links and added the required links. Could you please review and merge this update?

Thanks, monish-j

**Comment by plon-Susk7** [comment]
Hi @monish-j , could you please pull the latest changes and then push?

**Comment by monish-j** [comment]
Hi  plon-Susk7,

I have pulled the latest changes from the main branch and updated the repos.yml file. Additionally, I have added 10 new YC open source company links. Could you please review and merge this update?

Thanks, monish-j
