### ISSUE TITLE
Add search functionality 

### ISSUE THREAD

**Issue by plon-Susk7** [plon-Susk7/Job-Board#6]
This is how the top of our body looks right now.
![image](https://github.com/user-attachments/assets/3e8df413-21e6-4756-9a31-4d3d4c8795b8)

We need to add a search bar for the user to search through the repositories listed. Further details can be discussed in this issue.

**Comment by 0xTaneja** [comment]
@plon-Susk7 review my pr when you have time and would love your suggestions/feedback!!
